### ISSUE TITLE
CoMapeo / Design changes

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#1125]
## Design Changes
List of design changes todo for the MVP

## ToDo

- [x] CoMapeo logo
- [x] Buttons
- [x] Colors

## Design assets

**Comment by macandrow** [comment]
![comapeo_logo_circle](https://github.com/digidem/mapeo-mobile/assets/7634137/165b5f2d-72fa-4753-9460-21e97eee1e79)
![Welcome Screen Topographical Lines](https://github.com/digidem/mapeo-mobile/assets/7634137/7f5fbfea-06c8-40fd-9745-09a2cdfa6e4e)
![Welcome Screen Topographical Lines (with bg)](https://github.com/digidem/mapeo-mobile/assets/7634137/929b71aa-cafb-4278-9a05-746b68f4abd6)

Svgs for welcome screens
2 versions of the topographical lines, 1 with transparent background, 1 with white background
