### ISSUE TITLE
No project/ Sync

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#1134]
## No project/ Sync
-  User first opens the app, they are on an unnamed unofficial project by themselves. 
-  let them know that they won’t be able to sync their observations until they create or join a project.

<img width="289" alt="Screen Shot 2023-10-04 at 2 46 54 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/c180ae32-f669-4130-9827-6ed0b8434816">

## Todo
- [ ] Display text box with copy **You won’t be able to share observations collected yet. To sync and share with other devices**
- [ ] Create `Create or Join a Project` button

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1200-69&mode=design&t=xfOwkkUA7kBhB7vK-0

## Copydeck
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1197-17493&mode=design&t=ojmacHaDmI1ARJ5k-0

**Comment by ErikSin** [comment]
Closing this issue as I have recreated it in the proper repo: https://github.com/digidem/comapeo-mobile/issues/317
