### ISSUE TITLE
Update Mapbox token to be injected at build time

### ISSUE THREAD

**Issue by ErikSin** [digidem/mapeo-mobile#1147]
The mapbox [access token](https://docs.mapbox.com/help/glossary/access-token/) is needed to download maps from mapbox. We currently hardcode an access token in our source code. 

## Problem
Mapbox [charges based on downloads](https://www.mapbox.com/pricing#map-loads-for-web) associated with access tokens. Due to our access token being available in our source code, anyone can copy and paste our access token, and Digital Democracy will be charged for those downloads.

In order to solve this, we can hide the access token and have it injected into the app in the dev and production builds.

#Proposed solution
- Save the access token as a [secret in bitrise](https://devcenter.bitrise.io/en/builds/secrets.html)

**Comment by achou11** [comment]
Closed via #1150
