### ISSUE TITLE
Error monitoring & reporting

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-mobile#129]
We need a system for reporting errors in Mapeo Mobile. Often errors are hard to replicate on developer devices, and getting reliable logging from phones in the wild is hard. An online error reporting service could allow us to collect stack traces and errors from phones "in the wild" where Mapeo is installed. We should add a clear opt-in/out to the app for reporting errors.

A few services we could use are:

- [bugsnag](https://www.bugsnag.com/)
- [Sentry](https://sentry.io/welcome/)
- [Rollbar](https://rollbar.com)
- [Crashlytics](https://rnfirebase.io/docs/v5.x.x/crashlytics/reference/crashlytics)

Sentry seems to be the "legacy" option that most people know. All of these options support React Native (importantly, they include both Native and JS reporting, which other options do not support).

I've reviewed the docs for the options above, and to me bugsnag is the easiest to understand, with clear instructions for setting everything up with React Native. It also seems to be well reviewed e.g. [this Reddit thread](https://www.reddit.com/r/reactnative/comments/a7kczu/status_of_react_native_crash_reporters_in_2019/). The other big pro of bugsnag is that they have clear & up-front [open-source free plans](https://www.bugsnag.com/open-source).

Any ideas or comments about what we should use? Ideally whatever we use for mobile we should also use for Desktop.

**Comment by okdistribute** [comment]
@gmaclennan is there a reason this was closed?
