### ISSUE TITLE
Cannot build on older android devices

### ISSUE THREAD

**Issue by czengg** [digidem/mapeo-mobile#16]
I'm on a Samsung S4 Android version 4.4.2. When I build the application, I am met with a blank white screen.

**Comment by staltz** [comment]
Hi, did you use Android SDK 26? I suppose the screen was white blank because Mapbox map component requires higher versions of Android. As long as this app uses Mapbox, the compatibility for older devices will follow what the Mapbox component is compatible with.

**Comment by gmaclennan** [comment]
It looks like Android 4.4.2 is API 19. From what I can find in the react-native and mapbox-gl repos it looks like react-native supports API 16 and above, as does mapbox-gl https://github.com/mapbox/react-native-mapbox-gl/issues/776

Is this a build problem maybe? How can we troubleshoot? We don't have many devices running Android 4.4 but it would be great if we could support them, and @czengg's old phone is maybe a good way of testing.

**Comment by staltz** [comment]
Logcat is the way to go. Can you check what it looks like as soon as the app opens into a blank screen?

**Comment by gmaclennan** [comment]
Unfortunately nodejs-mobile and the modules from expo that we use require minimum Android SDK 21, which is Android 5.0. We do not currently support < Android 5.0
