### ISSUE TITLE
Repeated breaks "oh dear something is broken"

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-mobile#220]
Using version 1.1.1-beta.8

On Samsung Galaxy Prime +

I installed a new background map, quite big (700MB) including mountain tiles of Sinangoe area. It repeatedly had errors loading the map, although sometimes it did load it, and I could not take and save any points. It would take me to save screen but when I press the save button nothing would happen and then it would quit shortly after with the 'oh dear' message in English. Reopening it would take me back to that screen which I could exit with back button, but did not manage to successfully save a point.

I then installed a smaller version on the 3 Sinangoe phones (moto, samsung, ulephone) and although there were initially similar issues, it did manage to load. It seemed to get better with time, ie, if I just left it open it would then work ok. But not sure what all the route of the problem is. 

If this is a known issue, maybe we need a note to this affect?

**Comment by ErikSin** [comment]
@aliya-ryan Im just trying to clean any thing that is over 2 years old. If this is still an issue can you please add it the techpriority list on notion with the given template! Thanks
