### ISSUE TITLE
Zooming in the map, it stays for a few seconds zoomed and then it zooms out by itself

### ISSUE THREAD

**Issue by marcoautiero** [digidem/mapeo-mobile#228]
I wonder if it is a desired behaviour. To me it seems rather strange: I zoom in, it stay on the new zoom level for a while (a couple of seconds) and then a zoom out happens with no apparent reasons.

Can we label it as an issue? Or, if the interaction must act in this way, please, can you explain me why? :)

**Comment by ErikSin** [comment]
Closed due to inactivity of 2 years
