### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by okdistribute** [digidem/mapeo-mobile#240]
- Currently most strings are hard-coded in Spanish.
- Should use react-intl v3 for all strings and dates etc.
- Should use babel-plugin-react-intl-auto to simplify translation ID management
- Strings shoudl include a contextual description (as a comment, which is extracted by the babel plugin) for translators
- Should use https://github.com/digidem/extract-react-intl-messages for extracting messages _with descriptions_ to ease translation.

**Comment by arky** [comment]
@okdistribute Could we integrate translation of custom icon names and category names into mapeo-mobile localization workflow as well.

**Comment by gmaclennan** [comment]
This is done, apart from #340. I'm closing this and we'll track category name translation in #340.
