### ISSUE TITLE
Set encryption key to Project ID

### ISSUE THREAD

**Issue by noffle** [digidem/mapeo-mobile#251]
This is a TODO for once we get project IDs into Mapeo. It basically amounts to initializing mapeo-core with an opts like

`{ encryptionKey: projectId }`

This will make the replication protocol encrypt all messages using the symmetric key `projectId`.

**Comment by noffle** [comment]
This will need to be coordinated with Mapeo Desktop, Mapeo Mobile, and Mapeo Web to ensure that it's deployed to everybody to ensure sync continues to work well.

*Or*, we could bump the mapeo protocol version in the peer handshake, and have new clients fall back to the common key if it's an old version. This'd give us backwards compatibility, but it also means that an attacker could connect to us, claim to be an old version, and download potentially sensitive data.

**Comment by noffle** [comment]
One more TODO: pass `opts = { internetDiscovery: true }` into `mapeo-core`.

**Comment by noffle** [comment]
You'll also need the latest `osm-p2p` and `@mapeo/core` versions!

**Comment by gmaclennan** [comment]
`encryptionKey` is an opt for `kappa-core` not `mapeo-core`. `mapeo-core` expects a `kappa-osm` instance, which in turn expects a `kappa-core` instance - it's this kappa-core instance that requires the `encriptionKey` opt. At some point we need to clean up this little tangle of deps - it's hard to understand.

**Comment by noffle** [comment]
Sorry, my err: yes, kappa-core takes the `opts.encryptionKey` param.

**Comment by gmaclennan** [comment]
Fixed in 69163607c826d2e11177eb2b2d5b8e8455c2e4e3
