### ISSUE TITLE
Localization Complete: Nepali

### ISSUE THREAD

**Issue by arky** [digidem/mapeo-mobile#279]
The contributor from Nepal has translated mapeo-mobile into Nepali locale. Request pulling in this localizations strings from crowdin for further build testing. 

https://crowdin.com/project/mapeo-mobile/ne-NP#

**Comment by gmaclennan** [comment]
Hi Arky, I've been mainly offline in the Peruvian Amazon, so just seeing this now. I approved the translations so they are now in PR #272. There will be a test build of this PR, which you will be able to find here when it is ready: http://mapeo-apks.ddem.us/?prefix=dev/

The filename will have this commit hash as the seven characters after the word `release_`: `6fc974e`. I might not be on internet tomorrow and I can't wait until the build finishes so I can't send you a direct link, but it should appear there in about 30 mins.

**Comment by arky** [comment]
Nepali localization strings tested in QA builds. Closing this bug as resolved.
