### ISSUE TITLE
Support KaiOS Devices 

### ISSUE THREAD

**Issue by arky** [digidem/mapeo-mobile#294]
KaiOS is increasingly available in developing countries. These $100 devices are robust and reliable.  It could be possible to generate a package (zip) for KaiOS with minimal changes? 

https://github.com/kaiostech/sample-react

https://developer.kaiostech.com/getting-started/build-your-first-package-app

* KaiOS is variant of original Firefox OS

**Comment by gmaclennan** [comment]
It would be possible but not that easy. It looks like KaiOS runs a web view, and we could generate most of the UI with https://github.com/necolas/react-native-web directly from the existing code. The challenge would be getting mapeo-core running on KaiOS, which _might_ be possible if it supports service workers, but we have not tried running mapeo-core in a service worker / browser environment yet.

**Comment by arky** [comment]
I think it would very difficult at the current generation of KaiOS devices. Perhaps things might change in future. I am going to close this bug for now.
