### ISSUE TITLE
java.lang.UnsatisfiedLinkError in MainActivity

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-mobile#301]
## Error in Mapeo Mobile

**java.lang.UnsatisfiedLinkError** in **MainActivity**
couldn't find DSO to load: libv8executor.so caused by: couldn't find DSO to load: libfb.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.mapeo/lib-main/libc++_shared.so" is 64-bit instead of 32-bit

[View on Bugsnag](https://app.bugsnag.com/digital-democracy/mapeo-mobile/errors/5e3a43baf82ef5001be6fbca?event_id=5e3a43ba0055f36d670a0000&i=gh&m=ci)

## Stacktrace

    SoLoader.java:738 - com.facebook.soloader.SoLoader.doLoadLibraryBySoName

[View full stacktrace](https://app.bugsnag.com/digital-democracy/mapeo-mobile/errors/5e3a43baf82ef5001be6fbca?event_id=5e3a43ba0055f36d670a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by gmaclennan** [comment]
This is happening a lot, but only on one specific device type with manufacturer "OPPO". The device seems to be configured in Thai so this is probably related to @arky's trainings. According to https://github.com/facebook/react-native/issues/25490 this [might be a bug](https://github.com/facebook/react-native/issues/25490#issuecomment-521161256) in the "FunTouch OS" installer which can be fixed by updating the phone.

This also seems to be fixed with a workaround in https://github.com/facebook/SoLoader/pull/45 which requires us to force use of the latest SoLoader as described in https://github.com/facebook/react-native/issues/25490#issuecomment-534570333

Proposed resolution: Add resolution strategy to Mapeo `build.gradle`:

```java
configurations.all {
     resolutionStrategy {
       force "com.facebook.soloader:soloader:0.8.0"
     }
}
```

**Comment by arky** [comment]
@gmaclennan Interesting! Oppo is quite popular brand in Southeast Asia. There were couple of these devices at Thailand trainings. 

It is really difficult to get folks to update the device OS. :(

**Comment by arky** [comment]
@gmaclennan I quickly checked on Oppo F7 device, it runs mapeo without any issues. Will check if I could get my hands on other variants of this device.
![DSC_0145](https://user-images.githubusercontent.com/808895/76474221-8374d780-642d-11ea-9852-9605fd99d028.JPG)

**Comment by gmaclennan** [comment]
@arky I'll ping you when I build v2.1.0-beta for testing, I've included the fix above in the hope that it will fix things.
