### ISSUE TITLE
Return to same point in list of observations after editing an observation

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-mobile#305]
Using MM v2.0.0.beta

If I have a long list of observations and am scrolling through it, if I look at one of the observations detail and then return to the list it returns me to the same point that I left it. However if I edit an observation then when I save it returns me to the top of the list of observations. I would expect it to return me to the same place.

**Comment by okdistribute** [comment]
@gmaclennan is this done?

**Comment by gmaclennan** [comment]
Just tested and this is fixed in v5.1-RC
