### ISSUE TITLE
Nexus 7 Front Facing Camera 

### ISSUE THREAD

**Issue by arky** [digidem/mapeo-mobile#339]
Using mapeo-mobile on tablets with only single front facing camera is a problem. For instance, on Nexus 7 mapeo works but camera screen remains black. Perhaps react camera component doesn't recognize devices with front facing camera.

**Comment by gmaclennan** [comment]
This should be an easy fix, we can check if a back camera is available and default to front: https://docs.expo.io/versions/v36.0.0/sdk/camera/#cameragetavailablecameratypesasync-string

**Comment by gmaclennan** [comment]
Edit: not so easy after all, that check only reports for Web, not Android. I opened a [feature request](https://expo.canny.io/feature-requests/p/what-cameras-does-device-have) for it, but I don't think it's a priority for them. I could not find any other react-native libraries that report device cameras, so we would probably have to write our own.

If should not be too hard to write a small Native (Java) Module to do this, following [this guide](https://reactnative.dev/docs/native-modules-android) and using some of the suggestions about [how to get camera info in Java](https://stackoverflow.com/questions/26107696/android-java-detect-if-device-has-a-back-camera).

**Comment by arky** [comment]
Closing this bug as Nexus devices are no longer supported by Android build system used by Mapeo.
