### ISSUE TITLE
Sync error screens mapeo-v2.1.0-RC.760-QA-debug

### ISSUE THREAD

**Issue by jencastrodoesstuff** [digidem/mapeo-mobile#361]
Testing  mapeo-v2.1.0-RC.760-QA-debug.apk
(Note: this is a copied relevant portion of the [Mm testing script ](https://www.notion.so/digidem/Script-for-MAPEO-Mobile-QA-UPDATE-IN-PROGRESS-56fa80375bb94740913b002bf07c1609)
I hope this provides accurate and sufficient details about what parts of sync worked and didn't work.  Using [Y]es and [N]o identifiers to indicate if something performed as expected.
- [Y]  Connected device(s) display correct device type Icon and device name
- [Y]  Sync status button displays "Sync" indicating it is ready to sync
- [Y]  [On click] Sync  button initiates sync
- Initiating device
    - [N]  Sync status button displays sync progress status increasing over time
    - [N]  Sync status button displays sync progress status reaches 100%
    - [N]  Sync status button displays sync progress status indicates complete
    - Sync error
        - [N]  Sync status button displays sync progress status indicates error
        - [Y]  An error message appears
        - [N]  Error message is in device default language
        - Error message says ________
![Screenshot_20200402-140509_MapeoQA](https://user-images.githubusercontent.com/33264095/78298393-3782f300-7500-11ea-8c4c-bcfdee1e38b9.jpg)
![Screenshot_20200402-140517_MapeoQA](https://user-images.githubusercontent.com/33264095/78298428-49fd2c80-7500-11ea-9e81-a95191ecd106.jpg)
        - App crash behaviour _______
Clicking "Dismiss" returns to frozen sync screen 
Frozen sync screen behaviour: no app buttons work. device back button doesn't work.

Clicking "Reload" displays  ______
![Screenshot_20200402-140920_Mapeo QA](https://user-images.githubusercontent.com/33264095/78298779-fb03c700-7500-11ea-9c01-84d328b3d56a.jpg)
![Screenshot_20200402-141308_Mapeo QA](https://user-images.githubusercontent.com/33264095/78298845-1ec70d00-7501-11ea-8ea6-4cad0807e55e.jpg)

App Restart required:
    - Data transfer verification
        - From map screen
            - [Y]  new data from other device shows as points on a map
            - [Y]  [On click] point  button goes to the observation screen for that point
                - [Y]  ← button returns to map screen
        - From observation list
            - [Y]  Confirm with secondary syncing device that all new data has been received
            - [Y]  Confirm with secondary syncing device that all new edits to data have been received

________
- Secondary syncing device
    - [Y]  Sync status button displays sync progress status increasing over time
    - [Y]  Sync status button displays sync progress status reaches 100%
    - [Y]  Sync status button displays sync progress status indicates complete

    - Data transfer verification
        - From map screen
            - [Y]  new data from other device shows as points on a map
            - [Y]  [On click] point  button goes to the observation screen for that point
                - [Y]  ← button returns to map screen
        - From observation list
            - [Y]  Confirm with initiating syncing device that all new data has been received
            - [Y]  Confirm with initiating syncing device that all new edits to data have been received

**Comment by gmaclennan** [comment]
Fixed in RC.762 https://github.com/digidem/mapeo-mobile/pull/358#issuecomment-610298413
