### ISSUE TITLE
Yellow alert screen 

### ISSUE THREAD

**Issue by jencastrodoesstuff** [digidem/mapeo-mobile#362]
not doing anything while in standby map view,
looked back at device and saw a yellow footer on my screen

![Screenshot_20200402-174959_Mapeo QA](https://user-images.githubusercontent.com/33264095/78303558-e5939a80-750a-11ea-9396-4cc527e891cd.jpg)

clicked it... but have no ideat what to do with it. Dismiss makes it disappear. 
![Screenshot_20200402-174637_Mapeo QA](https://user-images.githubusercontent.com/33264095/78303497-c1d05480-750a-11ea-86f1-3cf6251e3f4d.jpg)

**Comment by gmaclennan** [comment]
@jencastrodoesstuff this is because you are using a development version of Mapeo Mobile and it is showing warnings (normally these are hidden). You can ignore these, but thanks for the heads up.
