### ISSUE TITLE
Map 'i" icon blocking scale

### ISSUE THREAD

**Issue by jencastrodoesstuff** [digidem/mapeo-mobile#363]
![Screenshot_20200402-135136_Mapeo QA(1)](https://user-images.githubusercontent.com/33264095/78303665-212e6480-750b-11ea-883a-682df27cbd39.jpg)

**Comment by gmaclennan** [comment]
Fixed in RC.762 https://github.com/digidem/mapeo-mobile/pull/358#issuecomment-610298413

Moves (i) to bottom-right.
