### ISSUE TITLE
Improve the formatting of Mapeo alerts

### ISSUE THREAD

**Issue by okdistribute** [digidem/mapeo-mobile#401]
Originally reported to include the date/time in the subject of mapeo alerts.

Any other features requested under the title of 'improving the formatting' ?

### Additional context 
https://faq.whatsapp.com/general/chats/how-to-format-your-messages?lang=ja

### Alert

Header, beginning of subject line in the message

E-mail subject

**Comment by jencastrodoesstuff** [comment]
Current email format
![Screen Shot 2020-07-02 at 1 45 05 PM](https://user-images.githubusercontent.com/33264095/86393070-785ae700-bc6a-11ea-8405-e23d3e3d374b.png)



Requested email format

- Subject: alert + category + observation date

- Body text format as shown which also works for Whatsapp

(Note: the date in the body text could equally be in the same line as the alert + category)

![Screen Shot 2020-07-02 at 1 42 59 PM](https://user-images.githubusercontent.com/33264095/86393119-9294c500-bc6a-11ea-9aec-cf1d3a5174bd.png)

**Comment by jencastrodoesstuff** [comment]
Requested Whatsapp format:
![Screen Shot 2020-07-02 at 1 42 23 PM](https://user-images.githubusercontent.com/33264095/86393374-f6b78900-bc6a-11ea-8c66-67655011823f.png)
 is scripted the same as shown on the Requested email format and as raw markup below
 :
```
MAPEO ALERT - _*Nature*_
May 17, 2020, 06:46 PM
UTM 18T 607885 5043327

*Nature Category* :
_Plant / Seed_
*Natural Resource* :
_Food_
*Common Name* :
_Parsley seeds_
*Proper Name / Story* :
_Italian Flat leaf Parsley_
_Petroseleniun crispum neapolitanum_

*Observer Name* :
_Jen_
*Affiliation* :
_Dd_

— Sent from Mapeo —
```

**Comment by jencastrodoesstuff** [comment]
Description text can be default with line breaks before and after. (Sorry my examples did not include description text. )
