### ISSUE TITLE
Observations do not show on the map if the GPS is off when the app starts

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-mobile#430]
**Steps to reproduce**
1. Close Mapeo completely
2. Turn off location services on the phone
3. Open Mapeo to map view

**Expected behaviour**
Observations show as points on the map

**Actual behaviour**
No observations show

**Workaround**
1. Turn on the phone GPS
2. Navigate to the sync screen
3. Navigate back to the map screen
(this forces the map to reload)

**Comment by okdistribute** [comment]
@gmaclennan is this still active or closed by #431?

**Comment by gmaclennan** [comment]
Closed by #431. This (and many other issues) should close when the 5.0.0 branch is merged with deploy.
