### ISSUE TITLE
Switching between different Mapeo app flavours on the same device can throw an error

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-mobile#434]
We publish different flavours of Mapeo: a "QA" version, a debug version, and a "WCMC-ICCA" version, as well as the public release version. All of these flavours use the same port for Mapeo Core. When the user switches from one app to another, Mapeo Core will close down and stop listening on the port. However, if the user rapidly switches from one flavour to another (e.g. switches from the production version to the QA version) then sometimes they will see an error (caused by Mapeo Core not stopping listening on the port before the next app tries to start listening).

**Comment by okdistribute** [comment]
Ah ha. This might be fixable by creating a new port number every time and passing that to the front end if necessary.

**Comment by gmaclennan** [comment]
Yes. We should switch to using IPC for everything we can (map resources will need to remain on http) for security reasons (currently other apps on the device and local network can read Mapeo data if they know the port number). When we do that we can use a random port (and also add a check in case the port is in use by another app). For now this is rare and only affects testers / developers who have multiple flavours installed and rapidly switch between them (you need to be quite fast to get it to fail).
