### ISSUE TITLE
Change settings page title in spanish to "Ajustes"

### ISSUE THREAD

**Issue by jencastrodoesstuff** [digidem/mapeo-mobile#457]
As I am writing instructions in Spanish I am realizing it is confusing to refer to "mapeo configurations" and "project configurations" as separate concepts with distinct functions.

 It would be much easier to train users using "Ajustes del aplicativo Mapeo" with "Ajustes" appearing in the page heading, and keep "Configuraciones del Proyecto" as is.

<img width="509" alt="Screen Shot 2020-09-08 at 2 58 10 PM" src="https://user-images.githubusercontent.com/33264095/92516836-c0a30200-f1e3-11ea-9c08-4fe8a7faa2a1.png">

@aliya-ryan any thoughts on this?

**Comment by aliya-ryan** [comment]
Yes @jencastrodoesstuff I agree whole-heartedly. Ajustes is a great word for this I think, and in English settings.

**Comment by jencastrodoesstuff** [comment]
@aliya-ryan  is updating this label on the crowd sourced translation platfor we are using (name escapes me now.

**Comment by okdistribute** [comment]
crowdin! Thanks @aliya-ryan  and @jencastrodoesstuff ! I see the [crowdin update here](https://github.com/digidem/mapeo-mobile/pull/436/files#diff-8ee5ebcd8cf6d6e8e09629f99891de1b).
