### ISSUE TITLE
terminating with uncaught exception of type std::bad_cast: std::bad_cast

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-mobile#517]
If Mapeo is failing to start, or quitting on startup, and you see this error in the logs (by running `npm run log`), then it is likely due to problems with NDK versions in the build.

CMake is used to build native modules for Node (leveldown and sodium) and it seems that CMake has a different mechanism for resolving which NDK version to use to Android.

Android has 3 mechanisms for specifying NDK versions:

1. `android.ndkversion` in `build.gradle`
2. `ANDROID_NDK_HOME` environment variable
3. `ANDROID_NDK_ROOT` environment variable

Some CI environments can specify one (or more) of these environment variables, and it seems like different tools will prioritize differently which one to use.

In addition, it seems like CMake can ignore all of these, and default to using the latest NDK version installed. If you search through the build logs for references to NDK you should see conflicts of versions e.g.

```
2021-02-11T21:34:47.5377010Z release|armeabi-v7a :CMake Warning at /Users/runner/Library/Android/sdk/ndk/22.0.7026061/build/cmake/android.toolchain.cmake:453 (message):
2021-02-11T21:34:47.5393400Z release|armeabi-v7a :-- Check for working C compiler: /Users/runner/Library/Android/sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
```

shows that CMake is using ndk r22 for the toolchain, even though everything else is configured to use r21. The workaround seems to be to delete all higher NDK versions before trying to build.

A more robust solution would be to find how to specify which NDK version CMake should use.

**Comment by ErikSin** [comment]
@gmaclennan has this been addressed?

**Comment by gmaclennan** [comment]
In a sense yes. The bug that remains is "Having NDK v22 installed during build-time will cause crash at runtime". The work-around is to delete NDK v22 before building. Android SDK allows several versions of NDK to be installed at the same time, and the build _should_ select the correct version based on Gradle config, but this is not working. This is a bug for people that need to have NDK v22 installed for other projects they are working on.

**Comment by gmaclennan** [comment]
Going to track in #744, closing here.
