### ISSUE TITLE
Internationalization for p2p upgrades text

### ISSUE THREAD

**Issue by hackergrrl** [digidem/mapeo-mobile#528]
@gmaclennan I'm not clear on what adding support for I18N on the p2p upgrades strings would entail. Is this something you'd be able to help with?

**Comment by gmaclennan** [comment]
I added a commit showing how this is done: https://github.com/digidem/mapeo-mobile/pull/524/commits/845c24a8b506250af7eda3682737f9e044fe5f7d

The key on `m` e.g. `m.checkingUpdates` is just internal to the file, it can be anything. `m.checkingUpdates.id` must be unique across the whole app, and translators see it in CrowdIn. I've been using the format you see to try to make something human readable. Translators also see `m.checkingUpdates.description` which gives a translator context for where the string appears. `m.checkingUpdates.defaultMessage` is the string you currently have in the component. As you can see I have replaced the string with `<FormattedMessage {...m.checkingUpdates} />`. This passes `id` and `defaultMessage` and `description` to the `FormattedMessage` component. It looks up a message `id` for translation according to the current locale, and if it is not translated it shows `defaultMessage`.

After adding new strings to the `defineMessages` functions, run `npm run extract-messages` which extracts new strings you have added and adds them to `messages/en.json` which read by CrowdIn (via a Github integration) for translation

**Comment by hackergrrl** [comment]
Are you able to do this work Gregor?

**Comment by gmaclennan** [comment]
This is done and pushed to the share-apk-p2p branch

**Comment by hackergrrl** [comment]
Thanks for clarifying!
