### ISSUE TITLE
Debounce or rate-limit progress events on p2p upgrade downloads

### ISSUE THREAD

**Issue by hackergrrl** [digidem/mapeo-mobile#529]
I think some logic that limits the code to only emit on each whole percent (%) integer. The code for this is on this line: https://github.com/digidem/mapeo-mobile/blob/share-apk-p2p/src/backend/lib/upgrade-server.js#L235

cc @gmaclennan -- is this something you could pick up?

**Comment by gmaclennan** [comment]
Yes, there are two performance bottlenecks:

1. Sending data over RnBridge has a performance hit (so sending lots of events will lock the bridge for other things)
2. Currently the front-end will re-render the screen every time it gets an updated progress, which can lock up the front-end.

What I have done for sync code is to throttle update events over the bridge to once every 500ms, which seemed high enough for the user to see updates: https://github.com/digidem/mapeo-mobile/blob/develop/src/backend/server.js#L85

I was looking to do this with the new code here: https://github.com/digidem/mapeo-mobile/blob/d8d67b3cc846f9690b9d1c481e73264dae4a8d2b/src/backend/server.js#L185-L196

We could throttle all events, but really we only want to throttle the progress event. As I commented in the PR, the current way that bound listeners are passed as arguments to the UpgradeManager constructor makes it hard to know where to apply the throttle.

Sorry for the rushed response! It got late in my day but I wanted to get back to you about this before I sign off.

**Comment by hackergrrl** [comment]
I think the best place to throttle is the download pipeline, linked to in my original post.

**Comment by hackergrrl** [comment]
Tracked now by https://github.com/digidem/mapeo-mobile/issues/538
