### ISSUE TITLE
(Front)  When click 'cancel' on the "Do you want to install this app?" modal

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#539]
**Description :**
Investigate possible react bug when hitting 'cancel' on the "Do you want to install this app?" modal

**Acceptance Criteria :**
TO ADD

**Technical Notes:**
TO ADD

**Points:**
3pts

**Comment by luandro** [comment]
I was finally able to track down the error with: `adb logcat | grep -A 10 -B 10 PackageInstaller`

```
04-29 09:44:05.582 25581 25581 W asset   : Asset path /data/user/0/com.mapeo.debug/files/upgrades/78ad74cecb99d1023206bf2f7d9b11b28767fbb9369daa0afa5e4d062c7ce041 is neither a directory nor file (type=0).
04-29 09:44:05.582 25581 25581 W PackageInstaller: Parse error when parsing manifest. Discontinuing installation
```

Other logs that might not be relevant:
```
04-29 09:32:32.122 17951 18819 E NODEJS-MOBILE:     filename: '/data/app/com.mapeo.debug-2/base.apk',
04-29 09:32:32.122 17951 18819 E NODEJS-MOBILE:     filename: '/data/user/0/com.mapeo.debug/files/upgrades/78ad74cecb99d1023206bf2f7d9b11b28767fbb9369daa0afa5e4d062c7ce041',
04-29 09:32:32.131 17951 18819 E NODEJS-MOBILE:     filename: '/data/app/com.mapeo.debug-2/base.apk',
04-29 09:32:32.131 17951 18819 E NODEJS-MOBILE:     filename: '/data/user/0/com.mapeo.debug/files/upgrades/78ad74cecb99d1023206bf2f7d9b11b28767fbb9369daa0afa5e4d062c7ce041',
```

**Comment by hackergrrl** [comment]
Glad you tested this -- I wonder if it's a phone thing? What phone are you using @luandro?

**Comment by luandro** [comment]
Me and @gregor did some digging and you're right Kira, it's related to phone version, in my case Android 6.

Opened a new issue #582 to investigate it.

**Comment by luandro** [comment]
#582 has been solved, so finally able to get started on this

Yet, I have no problem when clicking on "cancel".

@noffle you reported the bug right? Let's wait for #586 to be merged and and try to reproduce the bug.

**Comment by luandro** [comment]
#586 has been merged. Please report back in case the bug still happens. If it does, might be related do Android versions again.
