### ISSUE TITLE
(Front) Develop a testing plan

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#542]
**Description :**
Research on the testing plan. Ask what we need to know for the feature to be solid

G: Front-end testing: Setting up mocks in Jest is really hard, best wait for a new hire who hopefully has experience in this and can setup the testing framework for mobile
Back-end testing: add more robust tests for 3 upgrade managers. Someone else to review testing code.

L: Identifying bugs and which ones are ok to ship initially

**Acceptance Criteria :**
When we know what is considered a feature to be "final"

**Technical Notes:**
TO ADD

**Points:**
5pts

**Comment by hackergrrl** [comment]
Closing in favour of https://github.com/digidem/mapeo-mobile/issues/562.
