### ISSUE TITLE
(Front) Feature off by default

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#549]
**Description :** As part of a soft launch, the team has decided to release the feature in stages. First stage is to set the feature by default and give the option to turn it on.

- Set the feature off by default
- Display a screen explaining the feature + CTA to turn on

**Acceptance Criteria :**
It is done when... - TO ADD

**Technical Notes:**
Notes added by the tech team - TO ADD

Points:
5pts

**Comment by luandro** [comment]
Isn't this the same as #541?

**Comment by ximenabb** [comment]
> Isn't this the same as #541?
you are correct!

**Comment by luandro** [comment]
![toggle_p2p_updates](https://user-images.githubusercontent.com/693728/115451101-24b68b80-a1f3-11eb-8e29-a63b009114e8.gif)

Is this what we're aiming for?
