### ISSUE TITLE
Change to semver compatible version names

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-mobile#554]
Currently we have 3 types of APK releases, each with their own version name format:

1. **"Production" releases**: These have the format `{major}.{minor}.{patch}.{buildNumber}` where `buildNumber` is an integer that is guaranteed to increment for every build (including builds of the other "non-production" releases)
2. **Release Candidates**: Format `{major}.{minor}.{patch}-RC.{buildNumber}`. The `{major}.{minor}.{patch}` portion is the target production release version. Each subsequent build of an RC (e.g. for fixing bugs identified in QA) will keep the same `{major}.{minor}.{patch}` but `buildNumber` will increment.
3. **Internal test builds**: These are built for every PR against the `develop` branch, and they have the version format: `internal.{buildNumber}`. These are used to test a specific feature before a PR is merged.

The reason for including the build number in the production release version was originally to identify different builds from each other, for example if there was an error building a version that required a rebuild. However, Android also tracks the build number via "versionCode" and the library that we use for accessing this data, [`react-native-device-info`](https://github.com/react-native-device-info/react-native-device-info#readme) includes a method [`getReadableVersion()`](https://github.com/react-native-device-info/react-native-device-info#getreadableversion) that concatenates the version name and version code / build number.

These version names are not semver compatible, which makes parsing and comparing them difficult. I propose we change our version naming to [semver v2.0.0](https://semver.org) compatible:

1. **Production Releases**: Standard semver e.g. `{major}.{minor}.{patch}`. The user will still be shown `{major}.{minor}.{patch}.{buildNumber}` in the "About Mapeo" screen, via the [`getReadableVersion()`](https://github.com/react-native-device-info/react-native-device-info#getreadableversion) method.
2. **Release Candidates**: `{major}.{minor}.{patch}-RC+{sha7}`. Here `{major}.{minor}.{patch}` refers to the _pending_ release. `sha7` is the Git commit sha used for the build, shortened to 7 characters.
3. **Internal test builds**: `{major}.{minor}.{patch}-PR{pullRequestNumber}+{sha7}` where `pullRequestNumber` is the number of the PR that the build is built from, `sha7` as above. Here `{major}.{minor}.{patch}` would be most recently published production version that has been merged back into the `develop` branch.

For updates:

1. **Production Releases**: Should update to the next semver production release, and never anything else.
2. **Release Candidates**: Should update to the next RC that shares the same `{major}.{minor}.{patch}`, and any production release that is semver => `{major}.{minor}.{patch}` of the RC. The versionCode / build number should be used to determine updates if the two RC releases have the same version (but different `+{sha7}`)
3. **Internal test builds**: Should update to anything that matches `{major}.{minor}.{patch}-PR{pullRequestNumber}`, again using the versionCode / build number.

### Examples:

1. `1.0.0` should update to `1.0.1` and `1.2.0` but not to `1.0.0-RC`
2. `1.1.0-RC+9a6731e` should update to `1.1.0` and to `1.1.0-RC+19d986e` _if_ the build number of the latter is higher.
3. `1.0.0-PR571+eac5a0f` should update to `1.0.0-PR571+afc1a1b` _if_ the build number of the latter is higher. It should not update to `1.0.0-PR572+4667afc` or any other version that does not match `/$1\.0\.0-PR571/`.

### Alternative options

[Date-based (CalVer)](https://en.wikipedia.org/wiki/Software_versioning#Date_of_release) versioning is common, e.g. [manyverse](https://gitlab.com/staltz/manyverse/-/blob/master/CHANGELOG.md) uses a version of this. It can be easier to understand for end-users, however the data in semver could be useful for us in the future e.g. we may want to change how "automatic" updates are based on whether they are a major, minor or patch release.

**Comment by hackergrrl** [comment]
I think with the scheme you're describing we can drop the buildNumber, since RCs and internal builds will have a unique SHA hash each time.

Based on that, I wrote some code to experiment with, but we could also use as a base:

```js
const semver = require('semver')

function canUpgrade (myVersion, theirVersion) {
  // Prod vs Prod
  if (isProduction(myVersion) && isProduction(theirVersion)) {
    return semver.gt(theirVersion, myVersion)
  }

  // RC vs Prod
  if (isReleaseCandidate(myVersion) && isProduction(theirVersion)) {
    if (semver.gt(theirVersion, myVersion)) {
      // Regular semver rules
      return true
    } else if (semver.eq(theirVersion, myVersion)) {
      // Only allow if the commit hashes differ
      const my = semver.parse(myVersion)
      const their = semver.parse(theirVersion)
      return my.build[0] !== their.build[0]
    }
  }

  // Internal vs Internal
  if (isInternalBuild(myVersion) && isInternalBuild(theirVersion)) {
    if (semver.eq(myVersion, theirVersion)) {
      // Only allow if the commit hashes differ
      const my = semver.parse(myVersion)
      const their = semver.parse(theirVersion)
      return my.build[0] !== their.build[0]
    }
  }

  return false
}

function isProduction (v) {
  const version = semver.parse(v)
  return version.prerelease.length === 0
}

function isReleaseCandidate (v) {
  const version = semver.parse(v)
  return version.prerelease.indexOf('RC') !== -1
}

function isInternalBuild (v) {
  const version = semver.parse(v)
  return version.prerelease.length > 0 && /PR[0-9]+/.test(version.prerelease[0])
}

const ib = '1.0.0-PR.5721+eac5a0f'
const pr = '5.1.0'
const rc = '1.1.0-RC+9a673e'
console.log(isInternalBuild(ib), isReleaseCandidate(ib), isProduction(ib))
console.log(isInternalBuild(rc), isReleaseCandidate(rc), isProduction(rc))
console.log(isInternalBuild(pr), isReleaseCandidate(pr), isProduction(pr))

console.log(canUpgrade('1.0.0', '1.0.1-RC+9a671'))
console.log(canUpgrade('1.0.0-PR971+eac', '1.0.0-PR971+9a671'))
```

**Comment by gmaclennan** [comment]
This is great Kira! Thanks for this. I do think we need the build number though: how would you know which is the newer version, given the hashes differ? We also need to handle the case of a re-build of a production release, e.g. semver stays the same, but build number increments (we had this happen once, due to some kind of npm error that resulted in a broken package, and a rebuild fixed it).

What we would want is:

```js
console.log(canUpgrade('1.0.0-PR971+eac', '1.0.0-PR971+9a671')) // true
console.log(canUpgrade('1.0.0-PR971+9a671', '1.0.0-PR971+eac')) // false
```

**Comment by hackergrrl** [comment]
> I do think we need the build number though: how would you know which is the newer version, given the hashes differ?

Right, good point.

I still like the idea of incorporating it into the build info, so, `1.0.0+B117` would install over `1.0.0+B116`. It would let us centralize all of this version logick, and also handle the case you describe of a rebuild of a prod release.

**Comment by gmaclennan** [comment]
Yeah, although the reason for not putting it there was striving to have semver compatible versions, since [according to the spec](https://semver.org/#spec-item-10)

> Build metadata MUST be ignored when determining version precedence.

I was trying to move away from having the build as part of the version name, in part so that for users with regular builds the version they see is simpler (3 numbers, rather than 4)

I think the version logic can still be centralized, just passing both the version name and build number to the `canUpgrade` function.

**Comment by hackergrrl** [comment]
> > Build metadata MUST be ignored when determining version precedence.

I can't think of any consequences to breaking this. Also, we'll be treating newer build numbers as higher whether we embed it in the semver or not.

> I was trying to move away from having the build as part of the version name, in part so that for users with regular builds the version they see is simpler (3 numbers, rather than 4)

We can still do this, by omitting the build number where we show versions, or extracting it and showing it separately.

**Comment by gmaclennan** [comment]
Let's stick with what we have (build number separate), because unfortunately I missed this comment before merging #557, and changing this again takes about 3-4 hours of manually testing to make sure the version name is correct on all builds (I needed to set up a replica of our build pipeline & CI to do it).
