### ISSUE TITLE
(Back) Delete old upgrade binaries

### ISSUE THREAD

**Issue by hackergrrl** [digidem/mapeo-mobile#576]
Right now, after an APK is downloaded and installed, it remains in the `upgrades/` directory (see `backend/lib/upgrade-storage.js`) forever. Since our binaries are >60mb each, this could quickly add up.

The work here would be to have `UpgradeStorage` check for obsolete upgrades on start-up, and purge them. This could be done synchronously, or async with locks to avoid race conditions on the underlying storage.

**Comment by luandro** [comment]
@noffle @gmaclennan quick input on the plan for doing this is welcome.

I think doing it synchronously won't be much of a bottleneck since we'll just be reading and deleting.

- [ ] Read `storageDir` and check if there are more then one binary files
- [ ] If there are, check for the latest (is there code ready and tested for this?
- [ ] Delete other files that aren't the latest apk file

**Comment by gmaclennan** [comment]
@luandro I think it's important that this is async - we shouldn't underestimate how long it might take to delete 60Mb+ archives on an older phone, and we don't want to hold up the node process for that (it would block things like sync and indexing).

Other than that I think the plan looks good, although I think the delete logic should be to delete any APK that is <= the installed version. There is no need to keep around an APK that is already installed, even if it is the latest.

**Comment by hackergrrl** [comment]
I think it would be simpler and safer for this to be synchronous:

1. no chance of race conditions against the upgrade metadata on disk
2. easier to implement
3. easier to reason about

If we don't make it synchronous, I think it would be best to wrap UpgradeStorage operations in a read-write lock to avoid race conditions.

**Comment by hackergrrl** [comment]
> If there are, check for the latest (is there code ready and tested for this?)

You'll want to build a list of all downloaded upgrades that are older or equal to the current version (`this.version` within UpgradeStorage). You can compare versions using `semver.{gt,lt,gte,lte}()`. You can fetch what's on disk with `this.localUpgrades.get((err, options) => {}`.

**Comment by luandro** [comment]
@hackergrrl 
It seems `getAvailableUpgrades.get` and `getAvailableUpgrades.set` will force us to have to use async, or create sync functions that do the same, which might ignore the locks?

I'm writing the cleanup function on Storage's `constructor`, as there are also `mkdirp.sync` and `rimraf.sync` there, is that the right place? If we really need async, should we run the cleanup from `UpgradeManager` instead?

**Comment by hackergrrl** [comment]
@luandro Agreed re: not using sync & that it would require a lot of other work to make existing code also sync.

What do you think about having an async `UpgradeStorage#init()` function, that held a lock so the rest of its API would block until the async init finished? Something like:

```js
class UpgradeStorage {
  constructor (...) {
    // regular init stuff
    this.lock = rwlock()
    this.lock.writeLock(release => {
      this.init(release)
    })
  }

  init (cb) {
    // TODO: async version of the mkdir/rimraf stuff we already have
    // TODO: async code for cleaning up old versions
    cb()  // once both are done
  }

  anyOtherMethodThatTouchesStorage (cb) {
    this.writeLock(release => {
      // the same logic that's already there, but with a release() with the cb() at the end
    })
  }
}
```

This will ensure that the storage instance won't work until our async initialization logic is done, but also queue up the operations other parts of the codebase wish to perform on it. Thoughts?
