### ISSUE TITLE
p2p-update: Store updates in cache storage?

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-mobile#587]
For discussion:

Currently we store update APKs in the `files` dir on internal storage. We could store the updates in [Cache storage](https://developer.android.com/training/data-storage/app-specific#internal-create-cache) on internal storage.

Advantage: The user can clear cache storage without clearing files storage (which is where the Mapeo Core DB is stored) to make space on the device. Android will also automatically clear out cache storage if space is limited on the device.

Disadvantage: Android could clear out the cache storage, so an update that was downloaded but not installed could be deleted before it is installed.

**Comment by hackergrrl** [comment]
Another disadvantage is that it's additional work to do & test.

I think it makes sense to store upgrades in cache storage though, but as a v2 feature instead. For now, my plan was to wipe all downloaded upgrades <= your running version at app start-up.
