### ISSUE TITLE
(Front) Project Joiner - Leave project screen

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#619]
**Description :**
Project Joiner wishes to leave the current project on their device

- Via Settings/Project Configuration, PJ clicks on 'Leave Project'
- Leave Project screen displays: 
  - numbers of observations and data being deleted
  - numbers of photographs

- Check box to opt-in
  - If unchecked, user cannot proceed
- CTA Leave Project OR Cancel

- If user clicks on Leave Project
  - Loader screen appears, display number of observations deleted
  - Complete screen 
  - CTA 'Go Home'

OUT OF SCOPE
- number of unscynced observations
- 
**Screen**
[Here](https://www.figma.com/proto/ZOsM89L0xy0NUOCkuksJgq/OTF-%2B-UXFund?node-id=45949%3A49&scaling=scale-down-width&page-id=45808%3A2&hide-ui=1)
**Technical Notes:**

**Points:**
21 pts

**Comment by ErikSin** [comment]
@gmaclennan 

questions:
* Is there an API/method to determine the number of UNSYNCED observations.
* Is there documentation for the delete/unsync API (if not, I might need to go through it with you)?
