### ISSUE TITLE
(Front) Project Joiner - Sycing Screen

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#626]
**Description :**
Project Joiner clicks on 'Join and Sync'

**Screen is:**
DURING
- Loader
- Display of how many observations are sycing

COMPLETE
- Success message saying 'Complete'
- Display of the total of observations synced
- CTA titled 'Start Mapping' redirecting to the map

**Screen**
[Here
](https://www.figma.com/proto/ZOsM89L0xy0NUOCkuksJgq/OTF-%2B-UXFund?node-id=45829%3A83&scaling=scale-down-width&page-id=45808%3A2&hide-ui=1)

**Points**
13pts

**Comment by ErikSin** [comment]
@gmaclennan is there documentation for the sync API?
