### ISSUE TITLE
Longitude and Latitude as default Coordinate system 

### ISSUE THREAD

**Issue by arky** [digidem/mapeo-mobile#641]
The most common request we get while using Mapeo in SE. Asia is the ability to enter the observations manual co-ordinates using Latitude and Longitude (in places where GPS fix is not acquired).  Mapeo currently defaults to UTM system. 

Such Geo-coridnates could be taken from hand-held GPS systems that are more accurate and able get fixes under dense canopy and shadow of hill or mountain.

**Comment by achou11** [comment]
Related to https://github.com/digidem/mapeo-mobile/issues/632
