### ISSUE TITLE
Auto focus text inputs in Observations Details fields

### ISSUE THREAD

**Issue by emreiser** [digidem/mapeo-mobile#657]
Many new users struggle to figure out how to enter information in text fields within Observation Details. The field label and "placeholder" text are displayed above, but there is no indication that users need to tap within the white space below to access keyboard. (Unlike the placeholder text for the initial description field, placeholder text for Observation Details text fields is not displayed within the text area itself.)

For text fields in Observation Details, let's auto focus input so that cursor is visible and keyboard is opened.
 
Current view when arriving at a text field:
<img src="https://user-images.githubusercontent.com/3493841/127199817-1f6b3487-15f3-47dd-b733-d0805daecc1d.jpg" width=50% height=auto>

**Comment by ximenabb** [comment]
didnt see this issue and had created another one here : https://github.com/digidem/mapeo-mobile/issues/734
in sprint 8
