### ISSUE TITLE
(Front) Project Coordinator - Join Request

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#668]
**Description :**
Project Coordinator is on the Project Config screen and clicks on "Add Person". Coordinator scans the Participants QR Code and is unsuccessful. They ask the Participant to send them a join request instead. 
**Screen is:**
XXXX wants you to join XXXX

(DENY REQUEST)
(INVITE)

**Important**
Cancel/Back buttons takes back to the previous page ie in this case Qr Code screen
**Screen**
[Here
](https://www.figma.com/proto/ZOsM89L0xy0NUOCkuksJgq/OTF-%2B-UXFund?node-id=46972%3A741&scaling=scale-down-width&page-id=45808%3A2&hide-ui=1&starting-point-node-id=45857%3A2)
Points:

5pts

**Comment by achou11** [comment]
@ximenabb do we also want to include the success screen for this ticket? https://www.figma.com/proto/ZOsM89L0xy0NUOCkuksJgq/OTF-%2B-UXFund?node-id=47107%3A844
