### ISSUE TITLE
(Front) iOS research

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#670]
**Goal:**
Evaluate how close we would be to getting an iOS working app. Work has been done on Gregor's side.

**Acceptance Criteria**
- Provide documentation on your findings. Solutions proposed? How far did Gregor with making it workable on iOS? Do you see any red flags?
- Estimation of time needed to deliver a "working" app
- Estimation of time needed to review the App Store upload process
- Propose next steps

**Points:**
13pts

**Comment by achou11** [comment]
Added a notion doc with notes on this so gonna close
