### ISSUE TITLE
(Front) Project Joiner - Practice Mode State 

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#701]
**Description :**
Project Joiner first Mapeo launch , app will be set to Practice Mode. 
Frame appears on home screen (map)

**Screen is:**
Orange frame
Footer displaying copy
'Practice Mode' (official copy tbd)

**Design**
[Here
](https://www.figma.com/file/ZOsM89L0xy0NUOCkuksJgq/OTF-%2B-UXFund?node-id=47133%3A752)

**Points**
13pts

**Comment by achou11** [comment]
Addressed by #724
