### ISSUE TITLE
(Front) PJ- Practice Mode - Project Config.

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#702]
**Description** 
PJ goes to Settings and then Project Configuration
PJ is on the Project Config screen
Current Config + Project Key = blank as this is a practice mode

**Screen is:**
Project Configuration

Practice Mode
**Current Configuration:  TO DISCUSS W TEAM
Project Key:**
(Import Config)
(Leave Practice Mode)

**Design**
[Here](https://www.figma.com/file/ZOsM89L0xy0NUOCkuksJgq/OTF-%2B-UXFund?node-id=46823%3A2468)

**Points**
5PTS

**Comment by achou11** [comment]
The frame was addressed in #724 . Addressing the config details in #728

**Comment by achou11** [comment]
Addressed in #728
