### ISSUE TITLE
(Front) PJ - Leave Practice Mode

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#703]
**Description**
PJ goes to Settings and then Project Configuration
PJ is on the Project Config screen
PJ has the option to Create a project or Join a project

FLOW #1 -  CREATE PROJECT
PJ clicks on Create Project
PJ see the ["Keep my Observations" state](https://www.figma.com/file/ZOsM89L0xy0NUOCkuksJgq/OTF-%2B-UXFund?node-id=47417%3A930)
PJ can Delete or Keep their observations
PJ is taken to the home screen (map)

FLOW #2-  JOIN PROJECT
PJ clicks on Join Project
PJ is taken to the [Join Project flow](https://www.figma.com/file/ZOsM89L0xy0NUOCkuksJgq/OTF-%2B-UXFund?node-id=45808%3A52)
PJ successfully joins a project by clicking on "Join. and Sync"
PJ see the ["Keep my Observations" state](https://www.figma.com/file/ZOsM89L0xy0NUOCkuksJgq/OTF-%2B-UXFund?node-id=47417%3A930)
PJ can Delete or Keep their observations
PJ is taken to the home screen (map)

**Screen is:**
Practice Mode
Current Configuration
*if no config display Practice* (Copy tbd)
Project Key
*if no key display None* (Copy tbd)

Ready to leave Practice Mode?
Create or join a project below
Create a project
Join a project

**Design** 
[Here
](https://www.figma.com/file/ZOsM89L0xy0NUOCkuksJgq/OTF-%2B-UXFund?node-id=46856%3A870)
**Points**

**Comment by ErikSin** [comment]
@ximenabb I would give this 13+ points. I don't know if I have time to take it this week. @achou11 Do you think you will have time. If not, we can just move it to next sprint!

**Comment by achou11** [comment]
Think in addition to #704, I can work on this on Monday. My plan was to spend Tues-Fri focusing on #707 

I'd estimate either 8 or 13pts (probably closer to 8)
