### ISSUE TITLE
Converting Api file to Typescript

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#706]
Currently the Api.js (src/api.js) file is written with flow annotations.

This files needs to be converted in typescript from flow

**Points**
13pts

**Comment by ximenabb** [comment]
@ErikSin  this issue is open and in code review. should we move to our current sprint?

**Comment by ErikSin** [comment]
@ximenabb Yes, lets talk about this during the tech group hug on Monday. I think its done, I think gregor had some small concerns that were addressed, but I think got lost in the interwebs
