### ISSUE TITLE
unpacking mapeo-styles at build rather than runtime

### ISSUE THREAD

**Issue by karissa** [digidem/mapeo-mobile#71]
Right now, the rnnode app unpacks the mapeo-styles repo every time index.js is run but could we do this when the apk is built?

**Comment by noffle** [comment]
Styles are only unpacked if not present or if the version of the `mapeo-styles` module is bumped.

**Comment by noffle** [comment]
cc @gmaclennan on this. Gregor and I talked a bit about this and Gregor felt that the whole thing really ought to be a separate download process that happened when the app is first run, to keep the APK from getting too large.

Still, for small assets (very low res world vector tiles; presets), yeah, I'm down with this happening at build time!

**Comment by noffle** [comment]
Trying to be more concrete, I see two separate TODOs:

1. Unpack `mapeo-styles` at build time in mapeo-mobile.
2. Introduce an automatic downloader into mapeo-mobile that pulls down and installs styles from some predetermined URL.
