### ISSUE TITLE
Migrate to React Native 0.66

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#840]
Note from Gregor:

React Native 0.66 is out, so we can maybe migrate directly to that: [](https://reactnative.dev/blog/2021/10/01/version-066?ck_subscriber_id=887776426). Related: When I had tried to upgrade to RN 0.65 before, nodejs-mobile was not building correctly. In my experiments with building Realm I figured out why.

Points: 13

**Comment by achou11** [comment]
I have some early work for upgrading to 0.65 (think I was blocked by some Flipper-related issue). Not sure if worth creating a remote branch for vis right now but in case we need somewhere to potentially start
