### ISSUE TITLE
Error  when clicking on a dot on the Map screen

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#842]
**Description**
The View observation screen does open when clicking on a map point but an error is thrown

**Expected behavior**
The yellow error alerts ar expected as part of a RC build.  These error messages are not blocking. 

**Screenshots**
https://www.notion.so/digidem/QA-Script-MAPEO-Mobile-5-3-0-Sprint-8-2021-13557bfaa54a48e58e90ab00ad3bdbf6#5ece939bafdb416ca1bb50a1a92d66ea

**Version**
v5.3.0-RC

**Comment by achou11** [comment]
I don't think this would be an issue for the production build, which hides these warnings. From what I understand, since we're doing QA using the QA build, those warnings are not suppressed by default. correct me if i'm mistaken @gmaclennan

**Comment by ximenabb** [comment]
cc @emreiser for visibility. closing issue
