### ISSUE TITLE
Fix GitBook-GitHub-Crowdin integration 

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#871]
Via Emilie

"Mar and I are doing a push to publish a new version of our Mapeo support Materials on GitBook before the end of the year and unfortunately the GitBook-GitHub-Crowdin integration that Gregor patched together a few months ago for translations seems to be broken with the new platform updates by GitBook. He asked me to put it on your radar so we can plan for some of his or another tech team member's time to get it sorted."

**Comment by ximenabb** [comment]
To discuss with Gregor next week

**Comment by achou11** [comment]
Moved to https://github.com/digidem/mapeo-docs-new/issues/9
