### ISSUE TITLE
(Front) Directional arrow / Turn on and off

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#881]
**Description**
Upon fixing : https://github.com/digidem/mapeo-mobile/pull/646
In order for the directional arrow to properly work, the phone has to constantly check the direction which the phone is pointing. This means that much more battery life is being used.
With the use of the directional arrow, the battery use went from 0.07% to 0.22%, over 200% increase in battery use.
[Programs team has agreed to have it deactivate automatically after 3 min](url). However, we would need to find a away to turn it on or off if need beed.

*Todo*
From discussions with programs team, we have decided that we will use the simplest design so we can get it out of the door for our partners. We would like to revisit this in the future, with feedback from our partners. Specifically we would like to determine how it effects a mobile's battery life.

For now, the option to turn it on and off will live in the settings, where the user will be warned that the battery may be drained faster. 

*Designs*
![Frame 386](https://user-images.githubusercontent.com/67773827/150690591-449d4a6f-b2ee-41b6-8644-aedde53ce08b.png)

*Points*

**Comment by ximenabb** [comment]
@ErikSin tagging you for visibility, once design is done.

**Comment by achou11** [comment]
Closed via #914
