### ISSUE TITLE
Challenge synchronizing between mobile and desktop

### ISSUE THREAD

**Issue by jensNH** [digidem/mapeo-mobile#883]
Hello Mapeo

At Forests of the World, a small Danish environmental and development NGO working with indigenous and local communities' forest governance, we are looking for ways to collect forest data in the field with smartphones. 

Starting to test the use of Mapeo, which is very interesting, I am trying to synchronize between Mapeo on Android phone v5.3.1 - mapeo-default-settings v3.5.0 - and Mapeo desktop v5.4.0 - mapeo-default-settings 3.4.0 - and have met a challenge.  I have looked in the documentation and think that the projects should have the same titles. Does this require that I make a custom .mapeosettings package as described in the documentation or is there a simpler way?

Kind regards,
Jens N Hansen

**Comment by jensNH** [comment]
Synchronization works on other wifis than at work.

**Comment by rudokemper** [comment]
Glad to hear @jensNH! I was about to look into this more. Let us know if you have any other questions or if anything else comes up.
