### ISSUE TITLE
Delete Map

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#940]
**Description** User clicked on a bg map, sees list of offline areas, wants to delete map

**Screens**
Are you sure you want to remove XXXX
This map and offline areas attached to it will be deleted. This cannot be undone
Remove Map
Cancel

**Copydeck**
https://docs.google.com/spreadsheets/d/1Eco_G5hmAqnWW5NfzpAeeMgn8L5c61VO_PnkU7mSIRI/edit#gid=1850696440

**Design**
https://www.figma.com/file/sxz2NvysPVab6ZTqs6f57K/Cobra-Collective

**Comment by ErikSin** [comment]
To ask in team meeting, Api method
